name: GitHub Pages CI

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: All things angular
      uses: AhsanAyaz/angular-deploy-gh-pages-actions@1.4.0
      with:
        github_access_token: ${{ secrets.DEPLOY_TOKEN }}
        build_configuration: production
        base_href: /deezer-angular-client/
        deploy_branch: gh-pages
        angular_dist_build_folder: dist/deezer-angular-client
        
permissions:
  contents: write
